[tools]
python = "3.13.3"
uv = "0.7.2"

[env._.python]
venv.path = ".venv"

[tasks.lint]
run = "ruff check"
description = "check with ruff"

[tasks.generate-schemas]
run = "uv run scripts/generate-schemas.py"
description = "Generate schemeas from pydantic models"
